[project]
name = "pythonproject2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "black>=26.3.1",
    "mypy>=1.20.0",
    "pandas>=3.0.2",
    "requests>=2.33.1",
    "ruff>=0.15.9",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "isort>=8.0.1",
    "pytest-cov>=7.1.0",
]
test = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[black]
max-line-length = 119
exclude = ".git"

[isort]
max-line-length = 119

[flake8]
max-line-length = 119
ignore = ["E501"]
exclude = [".git"]

[tool.mypy]
python_version = "3.9"
strict = true
follow_imports = "silent"
ignore_missing_imports = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true
explicit_package_bases = true
namespace_packages = true
mypy_path = "src"

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true
